### PR TITLE
TST: install dependencies with Conda on py3.6 tests.

### PR DESCRIPTION
**Pull request by tswast**
Cover dependency installation via Conda in one of the CI tests.

Addresses https://github.com/pydata/pandas-gbq/pull/39#issuecomment-309157665

### CODE REVIEW

**Comment by tswast** [comment]
Note: Right now I'm getting a failure at https://travis-ci.org/tswast/pandas-gbq/jobs/245990533

```
$ if [ -f "$REQ.pip" ]; then pip install -r "$REQ.pip"; else conda install --file "$REQ.conda"; fi
Fetching package metadata ...........
PackageNotFoundError: Package missing in current linux-64 channels: 
  - google-auth
Close matches found; did you mean one of these?
    google-auth: google-apputils
```

I see the package at https://conda-forge.github.io/feedstocks, so I'm not sure what's going on.

**Comment by tswast** [comment]
Ah, per https://conda-forge.github.io/ I think I need to add `conda config --add channels conda-forge `

**Comment by tswast** [comment]
Looks like it is working now that I added the `conda-forge` channel. https://travis-ci.org/tswast/pandas-gbq/builds/245993672

**Comment by tswast** [comment]
Hmmm... `flake8` is failing now. I don't see how that could be related to this change. Maybe there was a change with flake8 versions.

**Comment by tswast** [comment]
I updated the Travis config to run lint in the non-conda version. Not sure what is going on, since flake8 runs fine in my local conda environment.

**Comment by tswast** [comment]
@jreback Is this what you had in mind?

**Comment by tswast** [comment]
Ping.

**Comment by parthea** [comment]
@jreback Here is a successful test run from tswast:conda :
https://travis-ci.org/tswast/pandas-gbq/builds/246001341

**Comment by jreback** [comment]
lgtm

also just review any references in install docs, readme, and pandas docs

if anything needs updating (separate pr)

**Pull request merged**
