### PR TITLE
TST: add mocked job_id for google-cloud-bigquery 0.29

### LINKED ISSUE #168: Tests failing on master
@tswast do you recognize these? https://travis-ci.org/pydata/pandas-gbq/jobs/364877445

I can't immediately see how 8f49ec3f134cc0a85f541116c42647c515fdc7e6 could have caused those

### PR DESCRIPTION
**Pull request by tswast**
Closes #168.

### CODE REVIEW

**Comment by maxim-lian** [comment]
I'm not sure how this could cause `E   ImportError: No module named pandas`?
https://travis-ci.org/pydata/pandas-gbq/jobs/370804286

**Comment by tswast** [comment]
I think the remaining failure is a regression of https://github.com/conda/conda/issues/5483 in how Conda handles namespace packages.

**Comment by tswast** [comment]
Sigh. Conda builds are still failing. I've tried removing everything that could be a bad interaction with conda and pip, but still no luck.

I think it really could be a regression in conda. To check that, I think the next step is to change
```
wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
```
to a pinned version. If that fixes it, we should file a bug against conda.

**Comment by tswast** [comment]
Whew, pinning `google-cloud-bigquery` fixed the conda build. I'll merge this so master gets green again.

I filed https://github.com/conda-forge/google-cloud-bigquery-feedstock/issues/10 to track it, but not sure when I can get to it to investigate further.

**Comment by maxim-lian** [comment]
Thanks a lot @tswast !

**Pull request merged**
