### PR TITLE
Remove console flow

### PR DESCRIPTION
**Pull request by maxim-lian**
The Console Flow is a strict subset of the functionality of the Local Webserver - if the browser fails to open, it's exactly the same. It makes writing parameterized tests harder, and is a small contributor to overall gunk

### CODE REVIEW

**Comment by maxim-lian** [comment]
Would close https://github.com/pydata/pandas-gbq/issues/53

**Comment by parthea** [comment]
Did you have any issue getting this to work on a headless machine? I cloned this branch on my headless machine and received an exception that the web server was already in use when trying to authenticate.  I like that the console flow allows you to easily authenticate in terminal if you're using `pandas-gbq` on a headless machine. 

```
>>> gbq.read_gbq('select 1','12345')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pandas_gbq/gbq.py", line 818, in read_gbq
    dialect=dialect)
  File "pandas_gbq/gbq.py", line 180, in __init__
    self.credentials = self.get_credentials()
  File "pandas_gbq/gbq.py", line 194, in get_credentials
    credentials = self.get_user_account_credentials()
  File "pandas_gbq/gbq.py", line 367, in get_user_account_credentials
    credentials = app_flow.run_local_server()
  File "/usr/local/lib/python2.7/dist-packages/google_auth_oauthlib/flow.py", line 407, in run_local_server
    host, port, wsgi_app, handler_class=_WSGIRequestHandler)
  File "/usr/lib/python2.7/wsgiref/simple_server.py", line 151, in make_server
    server = server_class((host, port), handler_class)
  File "/usr/lib/python2.7/SocketServer.py", line 417, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/wsgiref/simple_server.py", line 48, in server_bind
    HTTPServer.server_bind(self)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib/python2.7/SocketServer.py", line 431, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
```

**Comment by maxim-lian** [comment]
That's v weird. It works fine for me in headless:

```
In [1]: import pandas.io.gbq as gbq

In [2]: gbq.read_gbq('select 1 as a', project_id='sixty-capital', auth_local_webserver=True)
Please visit this URL to authorize this application: https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=495642085510-k0tmvj2m941jhre2nbqka17vqpjfddtd.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2F&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fbigquery&state=b0aQA29ZDoyHys[]PIViG&access_type=offline
```

Is yours a one-off or something repeatable? If the latter, we could deprecate and change the default, but leave the `False` option and see if it's widespread?

**Comment by tswast** [comment]
@craigcitro I believe I put the console flow in based on a conversation with you. Thoughts on this change?

**Comment by craigcitro** [comment]
In general, assuming that the user is at the same machine as the one running their python code is a faulty assumption IMO. That is, I don't believe that the local webserver flow handles all cases that the console flow does.

In particular, here's a simple recipe to reproduce: start a VM anywhere with only SSH access, connect from your laptop via SSH, and run `pandas-gbq`-using code there. Assuming you have not or cannot set up SSH forwarding of the right ports, there's no way for your laptop's web browser to talk to the local webserver running on your VM.

Or, a repro closer to my heart: open https://colab.research.google.com and try from there. There's no way for your local browser to talk to a random webserver started on that machine. (This is one of the reasons that we have some custom auth code in play.)

**Comment by maxim-lian** [comment]
@craigcitro when I try in a docker container (https://github.com/pydata/pandas-gbq/pull/140#issuecomment-370248513), it prints out a web address whether or not I pass `True` or `False` to `auth_local_webserver`, because it can't find a browser.

If it doesn't have that in some situations, then I 100% agree with you. My point is based only there being a fallback, rather than whether that fallback is required.

**Comment by craigcitro** [comment]
@maxim-lian It will always print out a web address; one of the query parameters in that address is the `redirect_uri`.

* If that uri is a real URL, eg `http://localhost:12345/...`, then when you click "authorize", your browser will send back a response containing your new oauth2 token to that URL. If that web request fails, there's no way to complete the authorization dance.

* If that uri is the "oauth2 OOB uri" (`urn:ietf:wg:oauth:2.0:oob`), then when you click "authorize", you'll get a code you can copy-paste back to the calling application. This application can then make a request to the oauth2 server (`accounts.google.com` in this case) to exchange that code for the oauth2 token and related bits.

So if you opt to go with the local server flow, and there's no way for your browser to communicate with that "local" server, then you can no longer do user-based authentication.

**Comment by maxim-lian** [comment]
@craigcitro Ah! I see. Even though the initial link is to `accounts.google.com`, it needs to redirect to `localhost`. Thanks for bearing with me.

Would you prefer the default stayed as-is?

**Comment by craigcitro** [comment]
@maxim-lian No problem at all! 😁 I've been doing oauth2-related things since, like 2011, and I still get confused regularly. (But hey, job security!)

I think *not* using a local webserver is the right default. My $0.02:
* local webserver: smoother when it works, but utterly confusing when it doesn't
* oob flow: clunkier, but always works

I've copy-pasted enough auth codes to last me a lifetime, but I don't fancy users getting stuck. WDYT?

**Comment by maxim-lian** [comment]
Super, agree. 

Closing

**Pull request closed without merging**
