### PR TITLE
Add anchor links to versions in the changelog

### PR DESCRIPTION
**Pull request by tswast**
Uses [Sphinx syntax for cross-reference labels](https://stackoverflow.com/a/19543591/101923).

### CODE REVIEW

**Comment by maxim-lian** [comment]
Thanks @tswast

**Comment by tswast** [comment]
Of course!

For posterity, I added these anchors so that I could link to them from the Pandas docs at https://github.com/pandas-dev/pandas/pull/21628

**Comment by maxim-lian** [comment]
Super!

I've been out of action on OSS recently given work, and heading on vacation for a couple of weeks. Hopefully I'll have more time in the Summer. Let me know if you see pandas-gbq issues that you think would be worth focusing on. Would be good for me to get something in re bulk download.

**Comment by tswast** [comment]
No worries. These are the top priorities on my mind for pandas-gbq:

1. Auth. https://github.com/pydata/pandas-gbq/issues/161 Basically, add a `client` parameter plus a couple public helper methods for auth and deprecate all the other auth-related parameters.
2. `to_gbq` configuration argument. Take in a job configuration dictionary, just like `read_gbq` does. It might make sense to officially deprecate the chunksize argument at that time, too. https://github.com/pydata/pandas-gbq/pull/124#discussion_r169198218
3. Delegate more to `google-cloud-bigquery` https://github.com/pydata/pandas-gbq/issues/149#issuecomment-400459052

Bulk download will be an interesting one to investigate. It does depend on GCS, so it'll likely have to be a separate `read_gbq_bulk` method, since we need a scratch bucket to work with. (Plus we'll have to update the scopes we use for authentication.)

**Pull request merged**
