### PR TITLE
Add more documentation to to_gbq() table_schema

### PR DESCRIPTION
**Pull request by melissachang**

### CODE REVIEW

**Comment by max-sixty** [comment]
Hi @melissachang - thanks for the PR. Looks like many of the diffs are formatting related. Are you OK to run `black` on the code? That should align most of the issues and highlight the actual diffs.
Let us know if you need any guidance!

**Comment by melissachang** [comment]
Done. Documenting my black command for my own reference: `~/anaconda3/bin/python3.6 $HOME/anaconda3/lib/python3.6/site-packages/black.py ~/pandas-gbq/pandas_gbq/gbq.py`

Just curious, why did you choose black over yapf? I'm thinking about switching for my repos.

**Comment by max-sixty** [comment]
> why did you choose black over yapf

I've generally had fairly bad results with yapf, particularly around arrays. Black is unambiguous and has very sensible defaults. There also feels like more community buy-in relative to yapf, and so a better train to jump on

**Comment by max-sixty** [comment]
Doc additions look good! You're welcome to add the change & self-attribution to the changelog. I'll merge tomorrow regardless.

**Comment by max-sixty** [comment]
Thanks @melissachang !

**Pull request merged**
