### PR TITLE
CLN: isort

### PR DESCRIPTION
**Pull request by maxim-lian**
Ran `isort -y`

Not worth enforcing I think, but occasional clean-ups (marginally) helpful

### CODE REVIEW

**Comment by maxim-lian** [comment]
@tswast could you merge as well as approve? I'm permissionless

**Comment by tswast** [comment]
@maxim-lian Merged.

I don't have admin permissions on this repo, but you've contributed enough that I think we should upgrade you if you're interested. 😃 @jreback can you do that?

**Comment by parthea** [comment]
@tswast @maxim-lian  Thanks for all your hard work, @maxim-lian! I've just added you as a collaborator with write permissions.

**Comment by maxim-lian** [comment]
Thanks @tswast and @parthea !

**Pull request merged**
