### PR TITLE
CLN: refactor auth logic to its own module.

### PR DESCRIPTION
**Pull request by tswast**
Uses new-style tests for auth-related tests. Also adds a couple additional auth-related tests for better coverage.

### CODE REVIEW

**Comment by tswast** [comment]
Travis build with credentials at https://travis-ci.org/tswast/pandas-gbq/builds/375140209

**Comment by tswast** [comment]
Oops. Looks like I need to update some of the monkey patches we used to skip auth in the unit tests and move over a few more tests from system/test_gbq.py to system/test_auth.py

**Comment by tswast** [comment]
Note: I borrowed the test marking idea for `local_auth` from #170. For the other kinds of credentials, I automatically skip in the fixture when the credentials can't be fetched.

Since there is more coverage for the other kinds of auth now, I think the rest of #170 might be unnecessary?

**Comment by maxim-lian** [comment]
Great!! Thanks so much for pushing all the way through on these. Both the main code and the tests are better.

Yes, I think we can close #170 now.

**Pull request merged**
