### PR TITLE
Support for replacing date partitioned tables

### PR DESCRIPTION
**Pull request by paoloburelli**
I addressed the enhancement request in #43, now it is possible to replace data in a partition. 
A few other minor changes have been added to give a full support of date partitioned tables (creation and insertion were missing mainly).
I also added a copy function, which is a convenient (and free) way to move data in BigQuery.

### CODE REVIEW

**Comment by parthea** [comment]
@paoloburelli Firstly, thanks for this PR! I think the next step for `pandas-gbq` is to leverage the work done in [google-cloud-bigquery](https://github.com/GoogleCloudPlatform/google-cloud-python/tree/master/bigquery/google/cloud/bigquery). I'd like to focus on migrating to `google-cloud-bigquery` before reviewing this PR since it already has support for some of the features proposed such as table copy operations. @jasonqng has done a great job getting this task started in PR #25.  @GregCT has also expressed interest in continuing the work done in PR #25 was recently added collaborator (based on the last comment in the PR).

I really appreciate the time that you put into this PR and I want to revisit it after #25 is merged because I agree these features would be helpful for the `pandas-gbq` community. If you're interested in helping out with #25, please let @jasonqng & @GregCT by commenting in PR #25.

cc @tswast
cc @jreback

**Comment by paoloburelli** [comment]
Hi, my team currently needs these changes, so we will continue to develop the library on our fork.
Meanwhile I will close this pull request and I'll monitor the development of the library.

**Comment by hayato1986** [comment]
Hope this goes to next step!

**Comment by BartVanDerVurst** [comment]
Will this be merged to the master soon? Still an open topic which results in errors when running data-partioning append's

**Comment by tswast** [comment]
@BartVanDerVurst there have been many changes to the pandas-gbq library since this PR was first created. For one, it now uses the `google-cloud-bigquery` library under the covers. It would need to be rebased on a more recent version of the library for us to merge it into master.

**Pull request closed without merging**
