### PR TITLE
BUG: fix read_gbq lost numeric precision

### PR DESCRIPTION
**Pull request by tworec**
fixes:
 - lost precision for longs above 2^53
 - and floats above 10k

Also contains  `test_gbq.py` clean up
- [x] tests added / passed
- [x] passes `git diff upstream/master | flake8 --diff`

### CODE REVIEW

**Comment by jreback** [comment]
@tworec looks good. waiting to see merged #9 so that testing looks good.

**Comment by tworec** [comment]
:ok_hand:

**Comment by jreback** [comment]
@tworec can you rebase

**Comment by tworec** [comment]
ok, done
it hurts.. please merge it at first occasion :)

**Comment by jreback** [comment]
thanks @tworec 

FYI, you have write to this repo so you can merge and such.

**Comment by tworec** [comment]
yeah, I know, thanks
but I think we need to cross-validate our code :)

**Comment by jreback** [comment]
hahah @tworec for sure!

**Pull request merged**
